//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRetailWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class тЗаказы
    {
        public int КодЗаказа { get; set; }
        public int КодКлиента { get; set; }
        public int КодТовара { get; set; }
        public int Количество { get; set; }
        public System.DateTime Дата_покупки { get; set; }
    
        public virtual тКлиенты тКлиенты { get; set; }
        public virtual тТовары тТовары { get; set; }
    }
}
