//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRetailWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class тТовары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public тТовары()
        {
            this.тЗаказы = new HashSet<тЗаказы>();
        }
    
        public int КодТовара { get; set; }
        public string Наименование { get; set; }
        public decimal Цена { get; set; }
        public Nullable<int> НаСкладе { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<тЗаказы> тЗаказы { get; set; }
    }
}
